Repository tloncorp/tlon-apps, pull requests merged in 2024-01, with the labels that each got.

#3153 groups: expose "can-read" as gate through scry
  desk/app/channels-server.hoon
  desk/app/diary.hoon
  desk/app/groups.hoon
  desk/app/heap.hoon
  desk/lib/channel-utils.hoon
Labels: performance

#3184 LAND-1059: Add contact on multi-DM join
  desk/app/chat.hoon
Labels: do not merge

#3193 LAND-1063: Preview contacts' favorite groups
  desk/app/groups.hoon
Labels: do not merge

#3188 various: remove old/stale/unused dependencies
  desk/app/chat.hoon
  desk/app/diary.hoon
  desk/app/groups.hoon
  desk/app/heap.hoon
  desk/app/notify.hoon
  desk/fixture.hoon
  desk/gen/diary/migrate.hoon
  desk/lib/diary-load.hoon
  desk/lib/group-store.hoon
  desk/lib/group.hoon
  desk/lib/groups-json.hoon
  desk/mar/channel-leave.hoon
  desk/mar/channel/outline.hoon
  desk/mar/channel/outlines.hoon
  desk/mar/group/init-0.hoon
  desk/mar/group/init-1.hoon
  desk/mar/group/init.hoon
  desk/sur/chat-0.hoon
  desk/sur/chat-1.hoon
  desk/sur/chat-2.hoon
  desk/sur/chat.hoon
  desk/sur/diary-0.hoon
  desk/sur/diary-1.hoon
  desk/sur/diary.hoon
  desk/sur/group-store.hoon
  desk/sur/group.hoon
  desk/sur/groups-0.hoon
  desk/sur/groups.hoon
  desk/sur/heap.hoon
  desk/sur/notify.hoon
  desk/tests/lib/diary-graph.hoon
  landscape-dev/lib/graph-store.hoon
  landscape-dev/sur/graph-store.hoon
  landscape-dev/sur/metadata-store.hoon
  landscape-dev/sur/post.hoon
  talk/sur/chat-0.hoon
  talk/sur/chat-1.hoon
  talk/sur/group-store.hoon
  talk/sur/group.hoon
Labels: ops/meta, devex
