Repository tloncorp/tlon-apps, pull requests merged in 2024-10, with the labels that each got.

#4049 Revert "fix sheet close animations (#4040)"
  apps/tlon-mobile/src/fixtures/ActionSheet/GenericActionSheet.fixture.tsx
  packages/ui/src/components/ActionSheet.tsx
  packages/ui/src/components/ChatOptionsSheet.tsx
Labels: next release

#4017 native: urbit auth recovery
  apps/tlon-mobile/package.json
  apps/tlon-mobile/src/components/AuthenticatedApp.tsx
  apps/tlon-mobile/src/screens/Onboarding/ReserveShipScreen.tsx
  apps/tlon-mobile/src/screens/Onboarding/ShipLoginScreen.tsx
  apps/tlon-mobile/src/screens/Onboarding/TlonLoginScreen.tsx
  apps/tlon-web-new/src/app.tsx
  package.json
  packages/app/contexts/ship.tsx
  packages/app/hooks/useConfigureUrbitClient.ts
  packages/app/lib/api.ts
  packages/app/lib/hostingApi.ts
  packages/shared/package.json
  packages/shared/src/api/urbit.ts
  pnpm-lock.yaml
Labels: do not merge

#4103 use bare text input for chat input
  packages/shared/src/logic/index.ts
  packages/shared/src/logic/tiptap.ts
  packages/ui/src/components/BareChatInput/helpers.ts
  packages/ui/src/components/BareChatInput/index.tsx
  packages/ui/src/components/BareChatInput/useMentions.tsx
  packages/ui/src/components/MessageInput/index.native.tsx
  packages/ui/src/components/MessageInput/index.tsx
  packages/ui/src/components/PostScreenView.tsx
  packages/ui/src/components/draftInputs/ChatInput.tsx
Labels: eas-build-ios:demo
