Repository tloncorp/tlon-apps, pull requests merged in 2025-03, with the labels that each got.

#4484 favorite-groups: dont leak secret groups
  apps/tlon-mobile/ios/Podfile.lock
  desk/app/groups.hoon
  packages/app/navigation/utils.ts
  packages/app/ui/components/ActionSheet.tsx
  packages/app/ui/components/FavoriteGroupsDisplay.tsx
  packages/app/ui/components/GroupSelectorSheet.tsx
Labels: next release, desk

#4508 negotiate: make note of simulated %kick danger
  desk/lib/negotiate.hoon
Labels: desk

#4517 Better Groups: implement preview response status
  desk/app/groups-ui.hoon
  desk/app/groups.hoon
  desk/lib/groups-json.hoon
  desk/lib/notify.hoon
  desk/mar/gangs-1.hoon
  desk/mar/gangs-2.hoon
  desk/mar/group/preview-2.hoon
  desk/mar/ui/init-6.hoon
  desk/sur/groups.hoon
  desk/sur/ui.hoon
Labels: desk

#4560 gallery: fix issue with shorter gallery posts in index
  packages/app/ui/components/Channel/Scroller.tsx
Labels: next release

#4559 remove deleted posts in galleries
  packages/app/features/top/ChannelScreen.tsx
  packages/app/ui/components/PostScreenView.tsx
  packages/shared/src/store/postActions.ts
  packages/shared/src/store/useChannelPosts.ts
  packages/shared/src/types/PostCollectionConfiguration.ts
Labels: next release

#4565 channel: display read-only notice if canWrite is false
  packages/app/ui/components/Channel/ReadOnlyNotice.tsx
  packages/app/ui/components/Channel/index.tsx
Labels: next release

#4564 embeds: fix issue with tall tweets not loading, and weird loading height issue
  packages/app/ui/components/Embed/EmbedWebView.tsx
Labels: next release

#4574 ChannelHeader: reflect connection state
  packages/app/ui/components/Channel/BaubleHeader.tsx
  packages/app/ui/components/Channel/ChannelHeader.tsx
Labels: next release

#4575 Add ability to join group by flag
  apps/tlon-mobile/ios/Podfile.lock
  packages/app/features/top/CreateChatSheet.tsx
  packages/app/hooks/useGroupSearch.ts
  packages/app/ui/components/ChatMessage/ChatMessageActions/Component.tsx
  packages/app/ui/components/GroupPreviewSheet.tsx
  packages/shared/src/api/apiUtils.ts
  packages/shared/src/store/dbHooks.ts
Labels: next release

#4563 verifier: verification and discovery service
  desk/app/lanyard.hoon
  desk/app/profile/widgets.hoon
  desk/app/verifier.hoon
  desk/desk.bill
  desk/mar/lanyard/command-1.hoon
  desk/mar/lanyard/query-1.hoon
  desk/mar/lanyard/update-1.hoon
  desk/mar/verifier/result.hoon
  desk/mar/verifier/update.hoon
  desk/mar/verifier/user-command.hoon
  desk/mar/verifier/user-query.hoon
  desk/sur/verifier.hoon
  desk/tests/app/verifier.hoon
  docs/verifier.md
Labels: desk

#4583 verifier, lanyard: compat with 410 jael vile scry
  desk/app/lanyard.hoon
  desk/app/verifier.hoon
  desk/sur/verifier.hoon
Labels: desk

#4577 native: revert showing unconfirmed posts in channel (#4280)
  apps/tlon-mobile/src/hooks/useNotificationListener.ts
  packages/app/ui/components/PostScreenView.tsx
  packages/shared/src/db/queries.ts
  packages/shared/src/store/useChannelPosts.ts
Labels: next release
