Repository tloncorp/tlon-apps, pull requests merged in 2025-04, with the labels that each got.

#4555 groups: correctly accumulate /epic %leave cards
  desk/app/groups.hoon
Labels: desk

#4630 desktop (mostly): react perf optimization
  apps/tlon-web-new/src/app.tsx
  packages/app/features/chat-list/ChatList.tsx
  packages/app/features/chat-list/GlobalSearch/index.tsx
  packages/app/features/top/ChannelScreen.tsx
  packages/app/features/top/ChatListScreen.tsx
  packages/app/hooks/useFilteredChats.ts
  packages/app/hooks/useRenderCount.ts
  packages/app/hooks/useResolvedChats.ts
  packages/app/navigation/BasePathNavigator.tsx
  packages/app/navigation/desktop/HomeNavigator.tsx
  packages/app/navigation/desktop/HomeSidebar.tsx
  packages/app/navigation/desktop/MessagesNavigator.tsx
  packages/app/navigation/desktop/MessagesSidebar.tsx
  packages/app/ui/components/ChatOptionsSheet.tsx
  packages/app/ui/components/GroupChannelsScreenView.tsx
  packages/app/ui/components/ListItem/ChannelListItem.tsx
  packages/app/ui/components/ListItem/ChatListItem.tsx
  packages/app/ui/components/ListItem/GroupListItem.tsx
  packages/app/ui/components/ListItem/InteractableChatListItem.tsx
  packages/shared/src/store/dbHooks.ts
  packages/ui/src/hooks/useIsWindowNarrow.ts
Labels: next release

#4642 desktop: fix issue with input height not adjusting for drafts
  packages/app/ui/components/BareChatInput/index.tsx
Labels: next release

#4645 db: make cache ids unique, remove unsupported extra conflict resolver
  packages/shared/src/db/migrations/0000_curious_squirrel_girl.sql
  packages/shared/src/db/migrations/meta/0000_snapshot.json
  packages/shared/src/db/migrations/meta/_journal.json
  packages/shared/src/db/migrations/migrations.js
  packages/shared/src/db/queries.test.ts
  packages/shared/src/db/queries.ts
  packages/shared/src/db/schema.ts
  packages/shared/src/store/sync.ts
Labels: next release

#4652 chat: show error state when s3 uploads fail
  packages/app/ui/components/BareChatInput/index.tsx
  packages/app/ui/components/MessageInput/AttachmentPreviewList.tsx
  packages/app/ui/components/MessageInput/MessageInputBase.tsx
Labels: next release

#4657 invite buttons: use copy rather than share on web
  packages/app/ui/components/InviteFriendsToTlonButton.tsx
  packages/app/ui/components/PersonalInviteButton.tsx
Labels: next release

#4658 desktop: make the sidebar skinnier
  packages/ui/src/index.ts
Labels: next release

#4644 expose: update for latest channels content types
  desk/app/expose.hoon
  desk/app/expose/page.hoon
  desk/app/expose/render.hoon
  desk/app/expose/widget.hoon
  desk/lib/channel-utils.hoon
Labels: desk

#4651 channels: add %link $block element
  desk/app/chat.hoon
  desk/lib/channel-json.hoon
  desk/lib/channel-utils.hoon
  desk/sur/channels.hoon
Labels: desk

#4666 gallery: handle ref attachments
  packages/app/ui/components/BigInput.tsx
Labels: next release, native, web

#4674 embeds: text formatted as a link shouldn't render an embed
  packages/app/ui/components/PostContent/contentUtils.tsx
Labels: next release

#4668 desktop: fix issue with chat input not allowing enter to send messages containing email addresses
  packages/app/ui/components/BareChatInput/index.tsx
  packages/app/ui/components/BareChatInput/useMentions.tsx
  packages/app/ui/components/MentionPopup.tsx
  packages/app/ui/components/MessageInput/InputMentionPopup.tsx
  packages/app/ui/components/MessageInput/MessageInputBase.tsx
  packages/app/ui/components/MessageInput/index.tsx
Labels: next release, web

#4663 desktop: use right click for sidebar context menus
  packages/app/features/top/GroupChannelsScreen.tsx
  packages/app/ui/components/GroupChannelsScreenView.tsx
  packages/app/ui/components/ListItem/ChannelListItem.tsx
  packages/app/ui/components/ListItem/GroupListItem.tsx
Labels: next release, web

#4678 desktop: fix link formatting in notebooks
  packages/app/ui/components/MessageInput/InputToolbar.tsx
Labels: next release, web

#4685 ImageViewerScreenView: image saving errors
  packages/app/ui/components/ImageViewerScreenView.tsx
  packages/app/ui/components/InviteFriendsToTlonButton.tsx
Labels: next release, native

#4684 OnboardingBenefitsSheet: close button, improved copy
  packages/app/ui/components/Onboarding/OnboardingBenefitsSheet.tsx
Labels: next release, native

#4687 web: fix titles
  apps/tlon-web/src/app.tsx
Labels: next release, web

#4694 profile: click-to-copy feedback
  packages/app/ui/components/UserProfileScreenView.tsx
Labels: native, web

#4616 ops: 410 compat
  desk/app/bait.hoon
  desk/app/bark.hoon
  desk/app/contacts.hoon
  desk/app/genuine.hoon
  desk/app/groups.hoon
  desk/app/growl.hoon
  desk/app/reel.hoon
  desk/desk.bill
  desk/lib/contacts.hoon
  desk/lib/contacts/json-0.hoon
  desk/lib/contacts/json-1.hoon
  desk/lib/reel.hoon
  desk/lib/summarize.hoon
  desk/mar/bait/acknowledge.hoon
  desk/mar/bait/describe.hoon
  desk/mar/bait/undescribe.hoon
  desk/mar/bark/add-recipient.hoon
  desk/mar/bark/receive-summary.hoon
  desk/mar/bark/remove-recipient.hoon
  desk/mar/contact-0.hoon
  desk/mar/contact-1.hoon
  desk/mar/contact.hoon
  desk/mar/contact/action-0.hoon
  desk/mar/contact/action-1.hoon
  desk/mar/contact/action.hoon
  desk/mar/contact/book-0.hoon
  desk/mar/contact/book.hoon
  desk/mar/contact/directory-0.hoon
  desk/mar/contact/directory.hoon
  desk/mar/contact/news.hoon
  desk/mar/contact/page-0.hoon
  desk/mar/contact/page-1.hoon
  desk/mar/contact/page.hoon
  desk/mar/contact/response-0.hoon
  desk/mar/contact/rolodex.hoon
  desk/mar/contact/update-0.hoon
  desk/mar/contact/update-1.hoon
  desk/mar/contact/update.hoon
  desk/mar/growl/summarize.hoon
  desk/mar/reel/bait.hoon
  desk/mar/reel/bite.hoon
  desk/mar/reel/command.hoon
  desk/mar/reel/confirmation.hoon
  desk/mar/reel/describe.hoon
  desk/mar/reel/description.hoon
  desk/mar/reel/give-token-link.hoon
  desk/mar/reel/metadata.hoon
  desk/mar/reel/undescribe.hoon
  desk/mar/reel/want-token-link.hoon
  desk/sys.kelvin
Labels: next release, desk

#4692 nav: specify screen to ensure proper nav
  apps/tlon-mobile/src/components/AuthenticatedApp.tsx
  packages/app/hooks/useNavigationLogger.ts
  packages/app/navigation/BasePathNavigator.tsx
  packages/app/navigation/utils.ts
Labels: web

#4689 fix "untitled group" issue
  desk/app/groups.hoon
  packages/app/hooks/useResolvedChats.ts
  packages/app/ui/components/ListItem/GroupListItem.tsx
  packages/app/ui/utils/channelUtils.tsx
  packages/shared/src/db/queries.ts
Labels: desk, native, web

#4686 fix: verify message delivery status after channel reaps
  packages/shared/src/db/queries.ts
  packages/shared/src/db/schema.ts
  packages/shared/src/store/postActions.ts
  packages/shared/src/store/sync.ts
Labels: native, web

#4690 ContactsScreen, ProfileNavigator: immediately add suggested contact
  packages/app/features/top/ContactsScreen.tsx
  packages/app/navigation/desktop/ProfileNavigator.tsx
  packages/app/ui/components/Badge.tsx
  packages/app/ui/components/ContactsScreenView.tsx
Labels: native, web

#4704 batch subscription events
  packages/shared/src/store/bufferedSubscription.ts
  packages/shared/src/store/sync.ts
Labels: next:web, next:native

#4714 onboarding: boot sequence fixes
  packages/app/hooks/useBootSequence.ts
Labels: next:native
