Repository tloncorp/tlon-apps, pull requests merged in 2025-08, with the labels that each got.

#4979 channels/server: ;; instead of !< for sequence nr pokes
  desk/app/channels-server.hoon
  desk/app/channels.hoon
  desk/tests/app/channels-server.hoon
  desk/tests/app/channels.hoon
Labels: next:backend

#4987 Robustly handle log replay at the client side
  desk/app/groups.hoon
Labels: next:backend, protocol-change

#4991 queue post edits
  packages/app/ui/components/BareChatInput/index.tsx
  packages/app/ui/components/PostScreenView.tsx
  packages/shared/src/domain/post.ts
  packages/shared/src/store/postActions.ts
Labels: next:web, next:native

#5003 press escape key to dismiss image viewer on web
  packages/app/ui/components/ImageViewerScreenView.tsx
Labels: next:web, next:native

#5029 chat: resequence chats to restore missing numbers
  desk/app/chat.hoon
Labels: next:backend

#5028 channels: content negotiation fixes
  desk/app/channels.hoon
  desk/tests/app/channels.hoon
Labels: next:backend

#5025 various: global /changes endpoints
  desk/app/channels.hoon
  desk/app/contacts.hoon
  desk/app/groups-ui.hoon
  desk/app/groups.hoon
  desk/mar/channel/changed-posts.hoon
  desk/mar/contact/changed-contacts.hoon
  desk/mar/group/changed-groups.hoon
Labels: next:backend

#4997 channels: prevent duplicate post sending
  desk/app/channels.hoon
  desk/tests/app/channels.hoon
Labels: next:backend

#5022 groups: delete tokens without crashing
  desk/app/groups.hoon
Labels: next:backend

#5021 groups: normalize channel kind in active-channels sync
  desk/app/groups.hoon
Labels: next:backend

#5013 channel-utils: best-effort kind-data downconvert
  desk/lib/channel-utils.hoon
Labels: next:backend

#5033 groups: properly handle group resubscription
  desk/app/channels-server.hoon
  desk/app/groups.hoon
Labels: next:backend

#5058 groups: robustly handle invalid seat updates
  desk/app/groups.hoon
Labels: next:backend

#4961 gallery: fix text rendering in gallery previews
  packages/app/ui/components/GalleryPost/GalleryPost.tsx
Labels: next:web, next:native

#5066 http-api: log scry status and size
  packages/shared/src/api/urbit.ts
  packages/shared/src/http-api/Urbit.ts
Labels: hotfix

#5063 mobile: prevent locking on splash screen
  apps/tlon-mobile/src/App.main.tsx
Labels: hotfix

#5057 groups: fixes for groups resubscriptions
  desk/app/groups.hoon
Labels: next:backend
