Repository tloncorp/tlon-apps, pull requests merged in 2025-05, with the labels that each got.

#4719 welcome: changes copy for last two steps
  cosmos.imports.ts
  packages/app/fixtures/SplashSequence.fixture.tsx
  packages/app/ui/components/Wayfinding/SplashSequence.tsx
Labels: next:native

#4720 SplashSequence, OnboardingStack: move contacts prompt to final Welcome step
  apps/tlon-mobile/src/OnboardingStack.tsx
  apps/tlon-mobile/src/screens/Onboarding/SetNicknameScreen.tsx
  apps/tlon-mobile/src/screens/Onboarding/ShareContactsScreen.tsx
  apps/tlon-mobile/src/types.ts
  cosmos.imports.ts
  packages/app/ui/components/Wayfinding/SplashSequence.tsx
Labels: next:native

#4721 groups agent: remove sort w/alphabetical ordering from drop-fleet
  desk/app/groups.hoon
  packages/app/ui/utils/channelUtils.tsx
Labels: next:backend, next:web, next:native

#4716 groups: implement -group-create thread
  desk/mar/group/create-thread.hoon
  desk/sur/groups-thread.hoon
  desk/ted/group/create.hoon
Labels: next:backend

#4713 android: group notifications by conversation
  apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/notifications/ActivityEvent.kt
  apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/notifications/NotificationManager.kt
  apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/notifications/TalkNotificationManager.java
Labels: next:native

#4727 mentions: fix multiline mentions, show nickname if possible
  packages/app/ui/components/BareChatInput/useMentions.tsx
Labels: next:web, next:native

#4665 notifications: render activity-event notifications using shared JS code
  apps/tlon-mobile/android/app/build.gradle
  apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/TalkMessagingService.java
  apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/notifications/ActivityEvent.kt
  apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/notifications/NotificationManager.kt
  apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/notifications/TalkNotificationManager.java
  apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj
  apps/tlon-mobile/ios/Landscape/AppDelegate.mm
  apps/tlon-mobile/ios/Notifications/NotificationPreviewPayload.swift
  apps/tlon-mobile/ios/Notifications/NotificationService.swift
  apps/tlon-mobile/ios/Podfile.lock
  apps/tlon-mobile/ios/Shared/Models/ActivityEvent.swift
  apps/tlon-mobile/ios/Shared/Models/Yarn.swift
  apps/tlon-mobile/ios/Shared/Networking/PocketNotificationsAPI.swift
  apps/tlon-mobile/ios/Shared/Notifications/PushNotificationManager.swift
  apps/tlon-mobile/src/hooks/useNotificationListener.ts
  packages/scripts/.gitignore
  packages/scripts/package.json
  packages/scripts/src/index.ts
  packages/scripts/tsconfig.json
  packages/shared/src/api/activityApi.ts
  packages/shared/src/logic/tiptap.ts
  packages/shared/src/urbit/activity.ts
  packages/shared/src/urbit/utils.ts
  pnpm-lock.yaml
  tsconfig.json
Labels: next:native

#4731 settings: set avatar/nickname calm preference
  packages/app/features/settings/PrivacyScreen.tsx
  packages/app/hooks/useCalmSettings.ts
  packages/shared/src/api/settingsApi.ts
  packages/shared/src/domain/analytics.ts
  packages/shared/src/store/dbHooks.ts
  packages/shared/src/store/settingsActions.ts
Labels: next:web, next:native

#4730 mentions: allow spaces
  packages/app/ui/components/BareChatInput/helpers.ts
  packages/app/ui/components/PostContent/InlineRenderer.tsx
  packages/app/ui/components/PostContent/contentUtils.tsx
  packages/shared/src/http-api/Urbit.ts
Labels: next:web, next:native

#4734 SplashSequence: new copy
  packages/app/ui/components/Wayfinding/SplashSequence.tsx
Labels: next:web, next:native

#4736 CreateChatSheet: grammatical consistency
  packages/app/features/top/CreateChatSheet.tsx
Labels: next:web, next:native

#4743 verifier: log twitter api responses
  desk/app/verifier.hoon
Labels: next:backend

#4700 expose: pinning to (in-app) profile
  desk/app/channels.hoon
  desk/app/expose.hoon
  desk/desk.bill
  desk/lib/channel-utils.hoon
  desk/ted/contact-pins.hoon
Labels: protocol-change

#4718 desktop: show user profile in ActivityNavigator
  packages/app/features/settings/EditProfileScreen.tsx
  packages/app/features/top/UserProfileScreen.tsx
  packages/app/navigation/desktop/ActivityNavigator.tsx
Labels: next:web

#4769 mobile: show confirmation alert when contact book import is successful
  packages/app/ui/components/SystemNotices.tsx
  packages/app/ui/components/Wayfinding/SplashSequence.tsx
  packages/shared/src/store/sync.ts
Labels: do not merge

#4781 mentions: handle mentions correctly across lines
  packages/app/ui/components/BareChatInput/helpers.ts
  packages/shared/src/logic/content-helpers.test.ts
  packages/shared/src/logic/content-helpers.ts
  packages/shared/src/logic/index.ts
Labels: next:web, next:native

#4695 scroller: move AuthorRow when deleting first message in sequence
  packages/app/ui/components/Channel/Scroller.tsx
Labels: next:native

#4732 profile: pressable ContactAvatar; icon: beefier cog
  packages/app/ui/components/UserProfileScreenView.tsx
  packages/ui/src/assets/icons/Settings.svg
Labels: next:native

#4733 settings: set theme on back-end, update across clients
  apps/tlon-web/src/state/settings.ts
  packages/app/features/settings/ThemeScreen.tsx
  packages/app/provider/index.tsx
  packages/app/types/theme.ts
  packages/app/ui/utils/index.ts
  packages/app/ui/utils/themeUtils.tsx
  packages/shared/src/api/settingsApi.ts
  packages/shared/src/domain/analytics.ts
  packages/shared/src/index.ts
  packages/shared/src/store/dbHooks.ts
  packages/shared/src/store/settingsActions.ts
  packages/shared/src/urbit/settings.ts
Labels: next:native

#4744 GroupRolesScreen: generate db-safe IDs for non-alpha-numeric role titles
  packages/app/features/groups/GroupRolesScreen.tsx
  packages/shared/src/logic/utils.ts
Labels: next:native

#4748 group settings: navigate back to chat details screen from leaf screens
  packages/app/features/groups/EditChannelScreen.tsx
  packages/app/features/groups/GroupMembersScreen.tsx
  packages/app/features/groups/GroupMetaScreen.tsx
  packages/app/features/groups/GroupPrivacyScreen.tsx
  packages/app/features/groups/GroupRolesScreen.tsx
  packages/app/features/groups/ManageChannelsScreen.tsx
  packages/app/features/top/ChatVolumeScreen.tsx
  packages/app/hooks/useChatSettingsNavigation.ts
  packages/app/navigation/GroupSettingsStack.tsx
  packages/app/navigation/types.ts
Labels: next:native

#4755 InlineRenderer: styling code blocks
  packages/app/ui/components/PostContent/InlineRenderer.tsx
Labels: do not merge, next:native, next-next:web

#4779 ChatOptionsSheet: disable channel leave for hosts
  packages/app/fixtures/ChatOptionsSheet.fixture.tsx
  packages/app/ui/components/ChatOptionsSheet.tsx
Labels: next:native, next-next:web

#4767 revert the revert of contact matching
  apps/tlon-mobile/ios/Podfile.lock
  apps/tlon-mobile/package.json
  packages/app/features/top/ContactsScreen.tsx
  packages/app/ui/components/ListItem/ChatListItem.tsx
  packages/app/ui/components/SystemNotices.tsx
  packages/shared/package.json
  packages/shared/src/api/contactsApi.ts
  packages/shared/src/api/lanyardApi.ts
  packages/shared/src/db/dbUtils.ts
  packages/shared/src/db/keyValue.ts
  packages/shared/src/db/migrations/0000_simple_vapor.sql
  packages/shared/src/db/migrations/meta/0000_snapshot.json
  packages/shared/src/db/migrations/meta/_journal.json
  packages/shared/src/db/migrations/migrations.js
  packages/shared/src/db/modelBuilders.ts
  packages/shared/src/db/queries.ts
  packages/shared/src/db/schema.ts
  packages/shared/src/domain/analytics.ts
  packages/shared/src/store/contactActions.ts
  packages/shared/src/store/lanyardActions.ts
  packages/shared/src/store/sync.ts
  packages/shared/src/urbit/lanyard.ts
  pnpm-lock.yaml
Labels: next:native

#4783 channels: retain mark types across protocol change
  desk/lib/channel-json.hoon
  desk/lib/channel-utils.hoon
  desk/mar/channel/response-1.hoon
  desk/sur/channels.hoon
Labels: protocol-change

#4791 content-helpers: make sure we extract the text for code blocks
  packages/shared/src/logic/content-helpers.test.ts
  packages/shared/src/logic/content-helpers.ts
Labels: next:web, next:native

#4765 link: previews
  apps/tlon-mobile/ios/Podfile.lock
  apps/tlon-web/src/logic/utils.ts
  apps/tlon-web/src/mocks/chat.ts
  apps/tlon-web/src/mocks/heaps.ts
  apps/tlon-web/vite.config.mts
  desk/app/metagrab.hoon
  desk/desk.bill
  desk/lib/channel-json.hoon
  desk/mar/channel/post-3.hoon
  desk/mar/channel/posts-3.hoon
  packages/app/fixtures/ActionSheet/AddGalleryPostSheet.fixture.tsx
  packages/app/ui/components/AddGalleryPost.tsx
  packages/app/ui/components/BareChatInput/index.tsx
  packages/app/ui/components/ChatMessage/ChatMessage.tsx
  packages/app/ui/components/Embed/EmbedContent.tsx
  packages/app/ui/components/GalleryPost/GalleryPost.tsx
  packages/app/ui/components/ImageViewerScreenView.tsx
  packages/app/ui/components/MessageInput/AttachmentPreviewList.tsx
  packages/app/ui/components/PostContent/BlockRenderer.tsx
  packages/app/ui/components/PostContent/contentUtils.tsx
  packages/app/ui/components/draftInputs/GalleryInput.tsx
  packages/app/ui/components/draftInputs/LinkInput.tsx
  packages/app/ui/components/draftInputs/shared.ts
  packages/app/ui/contexts/attachment.tsx
  packages/shared/src/api/__snapshots__/postsApi.test.ts.snap
  packages/shared/src/api/apiUtils.ts
  packages/shared/src/api/channelsApi.ts
  packages/shared/src/api/index.ts
  packages/shared/src/api/metagrabApi.ts
  packages/shared/src/api/postsApi.ts
  packages/shared/src/api/urbit.ts
  packages/shared/src/db/migrations/0000_natural_cable.sql
  packages/shared/src/db/migrations/meta/0000_snapshot.json
  packages/shared/src/db/migrations/meta/_journal.json
  packages/shared/src/db/migrations/migrations.js
  packages/shared/src/db/schema.ts
  packages/shared/src/db/types.ts
  packages/shared/src/domain/analytics.ts
  packages/shared/src/domain/attachment.ts
  packages/shared/src/domain/index.ts
  packages/shared/src/http-api/Urbit.ts
  packages/shared/src/logic/embed.ts
  packages/shared/src/logic/tiptap.ts
  packages/shared/src/logic/utils.ts
  packages/shared/src/store/index.ts
  packages/shared/src/store/metagrabActions.ts
  packages/shared/src/store/storage/storageActions.ts
  packages/shared/src/urbit/channel.ts
  packages/shared/src/urbit/content.ts
  packages/shared/src/urbit/groups.ts
  packages/shared/src/urbit/index.ts
  packages/shared/src/urbit/meta.ts
  packages/shared/src/urbit/metagrab.ts
  packages/shared/src/urbit/utils.ts
  packages/ui/src/components/Image.tsx
Labels: protocol-change

#4802 tiptap: dont change from code block -> inline code
  packages/app/ui/components/BigInput.tsx
  packages/shared/src/logic/tiptap.test.ts
  packages/shared/src/urbit/content.ts
Labels: protocol-change

#4821 embeds: store as rich link blocks
  packages/app/ui/components/BareChatInput/index.tsx
  packages/app/ui/components/ChatMessage/ChatMessage.tsx
  packages/app/ui/components/GalleryPost/GalleryPost.tsx
  packages/app/ui/components/PostContent/BlockRenderer.tsx
  packages/app/ui/components/draftInputs/LinkInput.tsx
Labels: next:web, protocol-change, next:native

#4805 ops: standardize cross-platform provider stack
  apps/tlon-mobile/src/App.main.tsx
  apps/tlon-web/src/app.tsx
  packages/app/provider/BaseProviderStack.tsx
  packages/app/provider/TelemetryProvider.native.tsx
  packages/app/provider/TelemetryProvider.tsx
Labels: next-next:native, next-next:web
