Repository tloncorp/tlon-apps, pull requests merged in 2025-07, with the labels that each got.

#4907 fix scrolling in create chat sheet
  packages/app/ui/components/ContactBook.tsx
Labels: next:web, next:native

#4897 UI: cosmetic omnibus
  apps/tlon-mobile/src/screens/Onboarding/GettingNodeReadyScreen.tsx
  apps/tlon-mobile/src/screens/Onboarding/InventoryCheckScreen.tsx
  cosmos.imports.ts
  packages/app/features/top/ChatListScreen.tsx
  packages/app/features/top/CreateChatSheet.tsx
  packages/app/fixtures/CreateChatSheet.fixture.tsx
  packages/app/fixtures/GroupListItem.fixture.tsx
  packages/app/ui/components/BareChatInput/index.tsx
  packages/app/ui/components/Channel/EmptyChannelNotice.tsx
  packages/app/ui/components/ChatMessage/ChatMessageActions/MessageActions.tsx
  packages/app/ui/components/ContactBook.tsx
  packages/app/ui/components/ListItem/ListItem.tsx
  packages/app/ui/components/NotebookPost/NotebookPost.tsx
  packages/app/ui/components/PersonalInviteSheet.tsx
  packages/app/ui/components/PostContent/BlockRenderer.tsx
  packages/app/ui/components/SearchBar.tsx
  packages/app/ui/components/StoppedNodePushSheet.tsx
  packages/app/ui/components/draftInputs/GalleryInput.tsx
Labels: next:web, next:native

#4887 mobile: fix certain emojis
  apps/tlon-web/src/logic/utils.ts
  packages/ui/src/components/Emoji/SizableEmoji.tsx
  packages/ui/src/components/Emoji/data.ts
  packages/ui/src/components/Emoji/utils.ts
Labels: next:native

#4909 BigInput: use actual uploaded image url for header image on send, disable post button while sending
  packages/app/ui/components/BigInput.tsx
Labels: next:web, next:native

#4868 web: use web-native list for chat channels
  packages/app/features/top/ChannelScreen.tsx
  packages/app/fixtures/Channel.fixture.tsx
  packages/app/fixtures/MessageActions.fixture.tsx
  packages/app/fixtures/useFixtureFeatureFlag.ts
  packages/app/lib/featureFlags.ts
  packages/app/ui/components/AuthorRow.tsx
  packages/app/ui/components/Channel/PostList/PostList.tsx
  packages/app/ui/components/Channel/PostList/PostList.web.tsx
  packages/app/ui/components/Channel/PostList/PostListFlatList.tsx
  packages/app/ui/components/Channel/PostList/index.ts
  packages/app/ui/components/Channel/PostList/shared.ts
  packages/app/ui/components/Channel/Scroller.tsx
  packages/app/ui/components/Channel/index.tsx
  packages/app/ui/components/Channel/useAnchorScrollLock.ts
  packages/app/ui/components/ChatMessage/ChatMessage.tsx
  packages/app/ui/components/ChatMessage/ChatMessageActions/Component.tsx
  packages/app/ui/components/ChatMessage/ChatMessageActions/types.ts
  packages/app/ui/components/DetailPostUsingContentConfiguration/contextmenu.tsx
  packages/app/ui/components/GalleryPost/GalleryPost.tsx
  packages/app/ui/components/NotebookPost/NotebookPost.tsx
  packages/app/ui/contexts/scroll.tsx
Labels: next:web

#4908 input: show link preview loading, don't block send
  packages/app/ui/components/BareChatInput/index.tsx
Labels: next:web, next:native

#4933 grouper: make sure we use the right mark and handle logging correctly
  desk/app/grouper.hoon
Labels: next:web

#4944 link input: fix URL validation issue
  packages/app/ui/components/PostContent/BlockRenderer.tsx
  packages/shared/src/logic/utils.ts
Labels: next:web, next:native

#4941 fix channels perms persistance issue
  desk/app/groups.hoon
  packages/shared/src/db/queries.ts
Labels: next:web, next:native

#4922 web: stabilize navigation when switching between narrow and wide navigators
  apps/tlon-web/src/app.tsx
  packages/app/navigation/BasePathNavigator.tsx
  packages/app/navigation/intent.test.ts
  packages/app/navigation/intent.ts
  packages/app/navigation/linking.ts
  packages/app/test/__mocks__/react-native.ts
  packages/app/ui/components/PostScreenView.tsx
  packages/app/vitest.config.ts
  packages/shared/src/db/keyValue.ts
Labels: next:web

#4952 MessageActions: only show admin edit for notebook posts themselves
  packages/app/ui/components/ChatMessage/ChatMessageActions/MessageActions.tsx
Labels: next:web, next:native

#4953 ActivitySummaryMessage: fix plurality for group join requests
  packages/app/ui/components/Activity/ActivitySummaryMessage.tsx
Labels: next:web, next:native

#4959 ChatOptionsSheet: make sure pane state is reset when the sheet/popover is closed.
  packages/app/ui/components/ChatOptionsSheet.tsx
Labels: next:web

#4954 ActionSheet: fix issue with unreliable button presses
  packages/app/ui/components/ActionSheet.tsx
  packages/app/ui/components/ChatOptionsSheet.tsx
Labels: next:web, next:native

#4962 InviteUsersWidget: disable users who are already members to prevent double-inviting
  packages/app/ui/components/InviteUsersWidget.tsx
Labels: next:web, next:native

#4972 desktop: handle tall popovers
  packages/app/ui/components/ActionSheet.tsx
Labels: next:web

#4965 ChatMessageActions: hide certain actions for !canWrite
  packages/app/ui/components/ChatMessage/ChatMessage.tsx
  packages/app/ui/components/ChatMessage/ChatMessageActions/Component.tsx
  packages/app/ui/components/ChatMessage/ChatMessageActions/MessageActions.tsx
  packages/app/ui/components/ChatMessage/ReactionsDisplay.tsx
  packages/app/ui/components/GalleryPost/GalleryPost.tsx
  packages/app/ui/components/NotebookPost/NotebookPost.tsx
  packages/shared/src/types/ChannelActions.ts
Labels: next:web, next:native
