Repository tloncorp/tlon-apps, pull requests merged in 2025-09, with the labels that each got.

#5090 threads: fix issue with reply messages delivered to main chat
  packages/shared/src/store/postActions.ts
  packages/shared/src/store/useChannelPosts.ts
Labels: next:web, next:native

#5094 ImageInput: show errors on upload, don't let users without configs attempt to upload
  apps/tlon-web/e2e/group-customization.spec.ts
  packages/app/ui/components/Form/inputs.tsx
Labels: next:web, next:native

#5018 stick to scroll bottom before caught up if user sends a post
  packages/app/ui/components/Channel/PostList/PostList.web.tsx
Labels: do not merge

#5081 group joins: fix issue where we falsely report that users don't have access to any channels
  packages/app/hooks/useGroupContext.ts
  packages/app/ui/components/ActionSheet.tsx
  packages/app/ui/components/GroupChannelsScreenView.tsx
  packages/app/ui/components/GroupPreviewSheet.tsx
  packages/app/ui/components/ListItem/listItemUtils.tsx
  packages/shared/src/api/groupsApi.ts
Labels: next:web, next:native

#5093 trigger stick-to-scroll-start when viewport height changes
  packages/app/ui/components/Channel/PostList/PostList.web.tsx
Labels: next:web

#5098 notify: minimal error case logging
  desk/app/notify.hoon
Labels: next:backend

#5091 logs: include commit hash from /commit.txt file
  .github/helpers/deploy.sh
  desk/app/logs.hoon
  desk/commit.txt
Labels: next:backend

#5103 AttachmentSheet: allow pasting image data from clipboard
  packages/app/ui/components/AttachmentSheet.tsx
  packages/app/ui/utils/clipboardUtils.ts
  packages/app/ui/utils/index.ts
  packages/ui/package.json
  pnpm-lock.yaml
Labels: next:native

#5111 unreads: fix flickering unread badge on channels
  packages/app/ui/components/Channel/index.tsx
Labels: next:web, next:native

#5097 remove webScroller feature flag, defaulting to enabled
  packages/app/fixtures/Channel.fixture.tsx
  packages/app/lib/featureFlags.ts
  packages/app/ui/components/Channel/PostList/PostList.web.tsx
Labels: next:web

#5110 lure: implement typed metadata fields
  desk/app/bait.hoon
  desk/app/grouper.hoon
  desk/app/reel.hoon
  desk/lib/reel.hoon
  desk/sur/reel.hoon
  desk/tests/app/bait.hoon
  desk/tests/app/grouper.hoon
  desk/tests/app/reel.hoon
Labels: next:next:backend

#5092 groups: fix logging core
  desk/app/groups.hoon
Labels: next:backend

#5123 GroupMembersScreenView: add filter input
  packages/app/ui/components/GroupMembersScreenView.tsx
Labels: next:web, next-next:native

#5128 Settings: hide "Log out" on desktop/web
  packages/app/ui/components/SettingsScreenView.tsx
Labels: next:web

#5119 channels/server: drop likely-bad (image) links
  desk/app/channels-server.hoon
  desk/app/channels.hoon
  desk/lib/channel-utils.hoon
  desk/tests/app/channels.hoon
Labels: next:backend
